import type { ArgTypes } from "@storybook/react-vite";

export const COMMON_ARG_TYPES:Partial<ArgTypes<Record<string, unknown>>> = {
animation: { control: 'select', options: ['none', 'spin', 'ping', 'pulse', 'bounce'] },
animationComposition: { control: 'select', options: ['replace', 'add', 'accumulate'] },
animationDelay: { control: 'text' },
animationDirection: { control: 'select', options: ['normal', 'reverse', 'alternate', 'alternate-reverse'] },
animationDuration: { control: 'text' },
animationFillMode: { control: 'select', options: ['none', 'forwards', 'backwards', 'both'] },
animationIterationCount: { control: 'text' },
animationName: { control: 'text' },
animationPlayState: { control: 'select', options: ['running', 'paused'] },
animationTimeline: { control: 'text' },
animationTimingFunction: { control: 'select', options: ['ease', 'ease-in', 'ease-out', 'ease-in-out', 'linear', 'step-start', 'step-end', 'steps', 'cubic-bezier', 'frames'] },
margin: { control: 'text' },
m: { control: 'text' },
marginTop: { control: 'text' },
mt: { control: 'text' },
marginBottom: { control: 'text' },
mb: { control: 'text' },
marginLeft: { control: 'text' },
ml: { control: 'text' },
marginRight: { control: 'text' },
mr: { control: 'text' },
marginX: { control: 'text' },
mx: { control: 'text' },
marginY: { control: 'text' },
my: { control: 'text' },
marginInlineStart: { control: 'text' },
marginInlineEnd: { control: 'text' },
marginBlockStart: { control: 'text' },
marginBlockEnd: { control: 'text' },
marginInline: { control: 'text' },
marginBlock: { control: 'text' },
padding: { control: 'text' },
p: { control: 'text' },
paddingTop: { control: 'text' },
pt: { control: 'text' },
paddingBottom: { control: 'text' },
pb: { control: 'text' },
paddingLeft: { control: 'text' },
pl: { control: 'text' },
paddingRight: { control: 'text' },
pr: { control: 'text' },
paddingX: { control: 'text' },
px: { control: 'text' },
paddingY: { control: 'text' },
py: { control: 'text' },
paddingInlineStart: { control: 'text' },
paddingInlineEnd: { control: 'text' },
paddingBlockStart: { control: 'text' },
paddingBlockEnd: { control: 'text' },
paddingInline: { control: 'text' },
paddingBlock: { control: 'text' },
hyphenateCharacter: { control: 'text' },
hyphenateLimitChars: { control: 'text' },
hyphens: { control: 'select', options: ['none', 'manual', 'auto'] },
hangingPunctuation: { control: 'select', options: ['none', 'first', 'last', 'first-line', 'last-line', 'all'] },
lineHeight: { control: 'text' },
lineBreak: { control: 'select', options: ['auto', 'loose', 'strict', 'anywhere'] },
letterSpacing: { control: 'text' },
orphans: { control: 'text' },
quotes: { control: 'select', options: ['none', 'normal', 'open-quote', 'close-quote', 'no-open-quote', 'no-close-quote'] },
rubyPosition: { control: 'select', options: ['none', 'start', 'end', 'space', 'center-line', 'space-around', 'with-ruby-text'] },
unicodeBidi: { control: 'select', options: ['normal', 'embed', 'isolate', 'bidi-override'] },
widows: { control: 'text' },
whiteSpace: { control: 'select', options: ['normal', 'nowrap', 'pre', 'pre-wrap', 'pre-line', 'break-spaces'] },
wordBreak: { control: 'select', options: ['normal', 'break-all', 'keep-all', 'break-word'] },
wordSpacing: { control: 'text' },
writingMode: { control: 'select', options: ['horizontal-tb', 'vertical-rl', 'vertical-lr'] },
font: { control: 'text' },
fontFamily: { control: 'text' },
fontFeatureSettings: { control: 'text' },
fontKerning: { control: 'text' },
fontLanguageOverride: { control: 'text' },
fontOpticalSizing: { control: 'text' },
fontPalette: { control: 'text' },
fontSize: { control: 'text' },
fontSizeAdjust: { control: 'text' },
fontStretch: { control: 'text' },
fontStyle: { control: 'text' },
fontSynthesis: { control: 'text' },
fontVariant: { control: 'text' },
fontVariantAlternates: { control: 'text' },
fontVariantCaps: { control: 'text' },
fontVariantEastAsian: { control: 'text' },
fontVariantEmoji: { control: 'text' },
fontVariantLigatures: { control: 'text' },
fontVariantNumeric: { control: 'text' },
fontVariantPosition: { control: 'text' },
fontVariationSettings: { control: 'text' },
fontWeight: { control: 'text' },
textAlign: { control: 'select', options: ['left', 'center', 'right', 'justify'] },
textAlignLast: { control: 'select', options: ['auto', 'left', 'center', 'right', 'justify'] },
textCombineUpright: { control: 'text' },
textDecoration: { control: 'text' },
textDecorationColor: { control: 'text' },
textDecorationLine: { control: 'text' },
textDecorationSkipInk: { control: 'text' },
textDecorationStyle: { control: 'text' },
textDecorationThickness: { control: 'text' },
textEmphasis: { control: 'text' },
textEmphasisColor: { control: 'text' },
textEmphasisPosition: { control: 'text' },
textEmphasisStyle: { control: 'text' },
textIndent: { control: 'text' },
textJustify: { control: 'text' },
textOrientation: { control: 'text' },
textOverflow: { control: 'text' },
textRendering: { control: 'text' },
textShadow: { control: 'text' },
textTransform: { control: 'text' },
textUnderlineOffset: { control: 'text' },
textUnderlinePosition: { control: 'text' },
width: { control: 'text' },
w: { control: 'text' },
minWidth: { control: 'text' },
minW: { control: 'text' },
maxWidth: { control: 'text' },
maxW: { control: 'text' },
height: { control: 'text' },
h: { control: 'text' },
minHeight: { control: 'text' },
minH: { control: 'text' },
maxHeight: { control: 'text' },
maxH: { control: 'text' },
display: { control: 'select', options: ['none', 'block', 'inline', 'inline-block', 'inline-flex', 'flex', 'grid', 'table', 'table-row', 'table-cell', 'table-caption', 'table-header-group', 'table-footer-group', 'table-row-group', 'table-column-group', 'table-column'] },
  overflow: { control: 'select', options: ['visible', 'hidden', 'scroll', 'auto', 'clip'] },
  overflowX: { control: 'select', options: ['visible', 'hidden', 'scroll', 'auto', 'clip'] },
  overflowY: { control: 'select', options: ['visible', 'hidden', 'scroll', 'auto', 'clip'] },
  position: { control: 'select', options: ['static', 'relative', 'absolute', 'fixed', 'sticky'] },
  zIndex: { control: 'number' },
  cursor: { control: 'text' },
  userSelect: { control: 'select', options: ['auto', 'text', 'none', 'contain', 'all'] },
  aspectRatio: { control: 'text' },
  boxSizing: { control: 'select', options: ['content-box', 'border-box'] },
  float: { control: 'select', options: ['left', 'right', 'none', 'inline-start', 'inline-end'] },
  clear: { control: 'select', options: ['none', 'left', 'right', 'both', 'inline-start', 'inline-end'] },
  objectFit: { control: 'select', options: ['fill', 'contain', 'cover', 'none', 'scale-down'] },
  objectPosition: { control: 'text' },
  resize: { control: 'select', options: ['none', 'both', 'horizontal', 'vertical', 'block', 'inline'] },
  verticalAlign: { control: 'text' },

  // Flex
  flexDirection: { control: 'select', options: ['row', 'row-reverse', 'column', 'column-reverse'] },
  flexDir: { control: 'select', options: ['row', 'row-reverse', 'column', 'column-reverse'] },
  justifyContent: { control: 'select', options: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly', 'start', 'end', 'left', 'right'] },
  justify: { control: 'select', options: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly', 'start', 'end', 'left', 'right'] },
  alignItems: { control: 'select', options: ['stretch', 'flex-start', 'flex-end', 'center', 'baseline', 'start', 'end', 'self-start', 'self-end'] },
  alignContent: { control: 'select', options: ['stretch', 'flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'start', 'end', 'baseline', 'first baseline', 'last baseline'] },
  alignSelf: { control: 'select', options: ['auto', 'flex-start', 'flex-end', 'center', 'baseline', 'stretch'] },
  flex: { control: 'text' },
  flexFlow: { control: 'text' },
  flexWrap: { control: 'select', options: ['nowrap', 'wrap', 'wrap-reverse'] },
  flexGrow: { control: 'number' },
  flexShrink: { control: 'number' },
  flexBasis: { control: 'text' },
  justifyItems: { control: 'text' },
  justifySelf: { control: 'text' },
  placeItems: { control: 'text' },
  placeContent: { control: 'text' },
  gap: { control: 'text' },

  // Color
  background: { control: 'text' },
  bg: { control: 'text' },
  backgroundColor: { control: 'text' },
  bgColor: { control: 'text' },
  color: { control: 'text' },
  borderColor: { control: 'text' },
  outlineColor: { control: 'text' },
  accentColor: { control: 'text' },
  caretColor: { control: 'text' },
  opacity: { control: 'number' },
  visibility: { control: 'select', options: ['visible', 'hidden', 'collapse'] },

  // Border
  border: { control: 'text' },
  borderWidth: { control: 'text' },
  borderTopWidth: { control: 'text' },
  borderBottomWidth: { control: 'text' },
  borderLeftWidth: { control: 'text' },
  borderRightWidth: { control: 'text' },
  borderStyle: { control: 'text' },
  borderTopStyle: { control: 'text' },
  borderBottomStyle: { control: 'text' },
  borderLeftStyle: { control: 'text' },
  borderRightStyle: { control: 'text' },
  borderRadius: { control: 'text' },
  borderTopLeftRadius: { control: 'text' },
  borderTopRightRadius: { control: 'text' },
  borderBottomLeftRadius: { control: 'text' },
  borderBottomRightRadius: { control: 'text' },
  borderTop: { control: 'text' },
  borderRight: { control: 'text' },
  borderBottom: { control: 'text' },
  borderLeft: { control: 'text' },
  borderX: { control: 'text' },
  borderY: { control: 'text' },
  borderStart: { control: 'text' },
  borderEnd: { control: 'text' },
  borderStartWidth: { control: 'text' },
  borderEndWidth: { control: 'text' },
  borderStartStyle: { control: 'text' },
  borderEndStyle: { control: 'text' },
  borderStartRadius: { control: 'text' },
  borderEndRadius: { control: 'text' },

  // Outline
  outline: { control: 'text' },
  outlineWidth: { control: 'text' },
  outlineStyle: { control: 'text' },
  outlineOffset: { control: 'text' },

  // Position
  top: { control: 'text' },
  right: { control: 'text' },
  bottom: { control: 'text' },
  left: { control: 'text' },
  inset: { control: 'text' },

  // Shadow
  boxShadow: { control: 'text' },

  // List
  listStyle: { control: 'text' },
  listStyleImage: { control: 'text' },
  listStylePosition: { control: 'text' },
  listStyleType: { control: 'text' },

  // Grid
  grid: { control: 'text' },
  gridArea: { control: 'text' },
  gridAutoColumns: { control: 'text' },
  gridAutoFlow: { control: 'text' },
  gridAutoRows: { control: 'text' },
  gridColumn: { control: 'text' },
  gridColumnEnd: { control: 'text' },
  gridColumnStart: { control: 'text' },
  gridRow: { control: 'text' },
  gridRowEnd: { control: 'text' },
  gridRowStart: { control: 'text' },
  gridTemplate: { control: 'text' },
  gridTemplateAreas: { control: 'text' },
  gridTemplateColumns: { control: 'text' },
  gridTemplateRows: { control: 'text' },
  gridGap: { control: 'text' },
  gridColumnGap: { control: 'text' },
  gridRowGap: { control: 'text' },

  // Column
  columnCount: { control: 'text' },
  columnFill: { control: 'text' },
  columnGap: { control: 'text' },
  columnRule: { control: 'text' },
  columnRuleColor: { control: 'text' },
  columnRuleStyle: { control: 'text' },
  columnRuleWidth: { control: 'text' },
  columnSpan: { control: 'text' },
  columnWidth: { control: 'text' },
  columns: { control: 'text' },

  // Contain
  contain: { control: 'text' },
  containIntrinsicBlockSize: { control: 'text' },
  containIntrinsicHeight: { control: 'text' },
  containIntrinsicInlineSize: { control: 'text' },
  containIntrinsicSize: { control: 'text' },
  containIntrinsicWidth: { control: 'text' },

  // Effect
  transition: { control: 'text' },
  transitionDuration: { control: 'text' },
  transitionProperty: { control: 'text' },
  transitionTimingFunction: { control: 'text' },
  transitionDelay: { control: 'text' },
  transform: { control: 'text' },
  transformBox: { control: 'text' },
  transformOrigin: { control: 'text' },
  transformStyle: { control: 'text' },
  clipPath: { control: 'text' },
  content: { control: 'text' },
  contentVisibility: { control: 'text' },

  // Mask
  mask: { control: 'text' },
  maskBorder: { control: 'text' },
  maskBorderMode: { control: 'text' },
  maskBorderOutset: { control: 'text' },
  maskBorderRepeat: { control: 'text' },
  maskBorderSlice: { control: 'text' },
  maskBorderSource: { control: 'text' },
  maskBorderWidth: { control: 'text' },
  maskClip: { control: 'text' },
  maskComposite: { control: 'text' },
  maskImage: { control: 'text' },
  maskMode: { control: 'text' },
  maskOrigin: { control: 'text' },
  maskPosition: { control: 'text' },
  maskRepeat: { control: 'text' },
  maskSize: { control: 'text' },
  maskType: { control: 'text' },

  // Background
  backgroundImage: { control: 'text' },
  bgImage: { control: 'text' },
  backgroundPosition: { control: 'text' },
  bgPosition: { control: 'text' },
  backgroundPositionX: { control: 'text' },
  bgPositionX: { control: 'text' },
  backgroundPositionY: { control: 'text' },
  bgPositionY: { control: 'text' },
  backgroundSize: { control: 'text' },
  bgSize: { control: 'text' },
  backgroundRepeat: { control: 'text' },
  bgRepeat: { control: 'text' },
  backgroundAttachment: { control: 'text' },
  bgAttachment: { control: 'text' },
  backgroundClip: { control: 'text' },
  bgClip: { control: 'text' },
  backgroundOrigin: { control: 'text' },
  bgOrigin: { control: 'text' },
  backgroundBlendMode: { control: 'text' },
  bgBlendMode: { control: 'text' },

  // Filter
  filter: { control: 'text' },
  backdropFilter: { control: 'text' },
}

